<nav>
    <div class="Menu">
        <a href="../../index.php">Accueil</a>
        <a href="ajoutBien.php">Ajouter des Biens</a>
        <a href="modifierBien.php">Modifier un Bien</a>
        <a href="supprimerBien.php">Supprimer un Bien</a>
        <a href="../ToutLesBiens.php">Liste des Biens</a>
        <a href="../RechercherBiens.php">Recherche de Biens</a>
        <a href="Statistiques.php">Statistiques</a>
        <a href="../Contact.php">Contact</a>
        <a href="../deconnexion.php">Déconnexion</a>
    </div>
</nav>