<nav>
    <div class="Menu">
        <a href="../index.php">Accueil</a>
        <a href="fonctionnalites/ajoutBien.php">Ajouter des Biens</a>
        <a href="fonctionnalites/modifierBien.php">Modifier un Bien</a>
        <a href="fonctionnalites/supprimerBien.php">Supprimer un Bien</a>
        <a href="ToutLesBiens.php">Liste des Biens</a>
        <a href="RechercherBiens.php">Recherche de Biens</a>
        <a href="fonctionnalites/Statistiques.php">Statistiques</a>
        <a href="Contact.php">Contact</a>
        <a href="deconnexion.php">Déconnexion</a>
    </div>
</nav>