<nav>
    <div class="Menu">
        <a href="index.php">Accueil</a>
        <a href="vuescontroleurs/fonctionnalites/ajoutBien.php">Ajouter des Biens</a>
        <a href="vuescontroleurs/fonctionnalites/modifierBien.php">Modifier un Bien</a>
        <a href="vuescontroleurs/fonctionnalites/supprimerBien.php">Supprimer un Bien</a>
        <a href="vuescontroleurs/ToutLesBiens.php">Liste des Biens</a>
        <a href="vuescontroleurs/RechercherBiens.php">Recherche de Biens</a>
        <a href="vuescontroleurs/fonctionnalites/Statistiques.php">Statistiques</a>
        <a href="vuescontroleurs/Contact.php">Contact</a>
        <a href="vuescontroleurs/deconnexion.php">Déconnexion</a>
    </div>
</nav>