/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pharmacie;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.text.DateFormatter;

/**
 *
 * @author sio2021
 */
public class CreerCommande extends javax.swing.JFrame {

    /**
     * Creates new form Commande
     */
    public CreerCommande() {
        initComponents();
        DefaultComboBoxModel listModel = new DefaultComboBoxModel();
        for (String unLibelle : Passerelle.donnerTousLesLibelleFournisseurs()) {
            listModel.addElement(unLibelle);
        }
        cmbFournisseur.setModel(listModel);
        
        lblDate.setText(String.valueOf(LocalDate.now()));
        
        DefaultComboBoxModel listModel2 = new DefaultComboBoxModel();
        for (String unLibelle : Passerelle.donnerTousLesLibelleMedoc()) {
            listModel2.addElement(unLibelle);
        }
        cmbMedoc.setModel(listModel2);
        
        DefaultComboBoxModel listModel3 = new DefaultComboBoxModel();
        for (String unLibelle : Passerelle.donnerTousLesLibelleEmployes()) {
            listModel3.addElement(unLibelle);
        }
        cmbEmploye.setModel(listModel3);
        
        lblNewIdCommande.setText(String.valueOf(Passerelle.getIdMaxCommande()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        btnQuitter = new javax.swing.JButton();
        lblIdCommande = new javax.swing.JLabel();
        lblIdFournisseur = new javax.swing.JLabel();
        Date = new javax.swing.JLabel();
        btnAjouter = new javax.swing.JButton();
        lblNbMedocs = new javax.swing.JLabel();
        lblQuantite = new javax.swing.JLabel();
        txtQuantite = new javax.swing.JTextField();
        lblIdEmploye = new javax.swing.JLabel();
        cmbFournisseur = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        cmbMedoc = new javax.swing.JComboBox<>();
        cmbEmploye = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        lblInfo = new javax.swing.JLabel();
        lblNewIdCommande = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnQuitter.setText("Quitter");
        btnQuitter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQuitterMouseClicked(evt);
            }
        });

        lblIdCommande.setText("idCommande");

        lblIdFournisseur.setText("idFournisseur");

        Date.setText("Date");

        btnAjouter.setText("Ajouter");
        btnAjouter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAjouterMouseClicked(evt);
            }
        });

        lblNbMedocs.setText("idMedicament");

        lblQuantite.setText("Quantité de médicaments");

        lblIdEmploye.setText("idEmploye");

        cmbFournisseur.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblDate.setText("Date du jour");

        cmbMedoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbEmploye.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblInfo.setText("            ");

        lblNewIdCommande.setText("lIdCommande");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAjouter)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(355, 355, 355)
                        .addComponent(btnQuitter))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblInfo))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblIdFournisseur)
                                .addComponent(lblIdCommande)
                                .addComponent(Date)
                                .addComponent(lblNbMedocs)
                                .addComponent(lblQuantite)
                                .addComponent(lblIdEmploye)))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtQuantite)
                            .addComponent(cmbFournisseur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1))
                            .addComponent(cmbMedoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbEmploye, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNewIdCommande))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdCommande)
                    .addComponent(lblNewIdCommande))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdFournisseur)
                    .addComponent(cmbFournisseur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Date)
                    .addComponent(jLabel1)
                    .addComponent(lblDate))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNbMedocs)
                    .addComponent(cmbMedoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantite)
                    .addComponent(txtQuantite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdEmploye)
                    .addComponent(cmbEmploye, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnQuitter)
                    .addComponent(btnAjouter))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuitterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuitterMouseClicked
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuitterMouseClicked

    private void btnAjouterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAjouterMouseClicked
        int idCommande = Integer.parseInt(lblNewIdCommande.getText());
        int idFournisseur = Passerelle.donnerUnIdFournisseur(String.valueOf(cmbFournisseur.getSelectedItem()));
        String date = String.valueOf(LocalDate.now());
        int idMedicament = Passerelle.donnerUnIdMedoc(String.valueOf(cmbMedoc.getSelectedItem()));
        int qt = 0;
        int idEmploye = Passerelle.donnerUnIdEmploye(String.valueOf(cmbEmploye.getSelectedItem()));
        boolean bool = true;
        
        try{
                qt = Integer.parseInt(txtQuantite.getText());
         }
         catch(Exception e){
                bool=false;
                lblInfo.setText("La quantité doit être une valeur numérique");
         }
        
         if(bool){
            Fournisseur unFournisseur=new Fournisseur(idFournisseur,null,null,null,null,null);
            Medicament unMedicament=new Medicament(idMedicament,null,null,0,null);
            Employe unEmploye = new Employe(idEmploye,null,null,0,null,null,0,null);
            Commande uneCommande=new Commande(idCommande,unFournisseur,date,unEmploye);
            DetailsCommandes unDetail=new DetailsCommandes(uneCommande,unMedicament,qt);
            boolean fonctionne=Passerelle.ajouterCommande(uneCommande);
            if(fonctionne){
                boolean bool2=Passerelle.ajouterDetailsCommandes(unDetail);
                if(bool2==true){
                    lblInfo.setText("Commande ajoutée");
                }
                else{
                    lblInfo.setText("Erreur lors de l'ajout de la quantité de médicament");
                }
            }
            else{
            }
        }   
    }//GEN-LAST:event_btnAjouterMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreerCommande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreerCommande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreerCommande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreerCommande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreerCommande().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Date;
    private javax.swing.JButton btnAjouter;
    private javax.swing.JButton btnQuitter;
    private javax.swing.JComboBox<String> cmbEmploye;
    private javax.swing.JComboBox<String> cmbFournisseur;
    private javax.swing.JComboBox<String> cmbMedoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblIdCommande;
    private javax.swing.JLabel lblIdEmploye;
    private javax.swing.JLabel lblIdFournisseur;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblNbMedocs;
    private javax.swing.JLabel lblNewIdCommande;
    private javax.swing.JLabel lblQuantite;
    private javax.swing.JTextField txtQuantite;
    // End of variables declaration//GEN-END:variables
}
