/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pharmacie;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.text.DateFormatter;

/**
 *
 * @author sio2021
 */
public class CreerDemande extends javax.swing.JFrame {

    private Employe unEmploye;
    
    
    public CreerDemande(String nom) {
        initComponents();
        
        lblDateJour.setText(String.valueOf(LocalDate.now()));
        
        DefaultComboBoxModel listModel2 = new DefaultComboBoxModel();
        for (String unLibelle : Passerelle.donnerTousLesLibelleMedoc()) {
            listModel2.addElement(unLibelle);
        }
        cmbMedoc.setModel(listModel2);
        
        lblNomEmploye.setText(nom);
        unEmploye=new Employe(1,nom,null,0,null,null,0,null);
        
        lblNewIdDemande.setText(String.valueOf(Passerelle.getIdMaxDemande()));
    }

    private CreerDemande() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        btnQuitter = new javax.swing.JButton();
        lblIdDemande = new javax.swing.JLabel();
        Date = new javax.swing.JLabel();
        btnAjouter = new javax.swing.JButton();
        lblNbMedocs = new javax.swing.JLabel();
        lblQuantite = new javax.swing.JLabel();
        txtQuantite = new javax.swing.JTextField();
        lblIdEmploye = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblDateJour = new javax.swing.JLabel();
        cmbMedoc = new javax.swing.JComboBox<>();
        lblNewIdDemande = new javax.swing.JLabel();
        lblInfo = new javax.swing.JLabel();
        lblNomEmploye = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnQuitter.setText("Quitter");
        btnQuitter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQuitterMouseClicked(evt);
            }
        });

        lblIdDemande.setText("idDemande");

        Date.setText("Date");

        btnAjouter.setText("Ajouter");
        btnAjouter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAjouterMouseClicked(evt);
            }
        });

        lblNbMedocs.setText("idMedicament");

        lblQuantite.setText("Quantité de médicaments");

        lblIdEmploye.setText("idEmploye");

        lblDateJour.setText("Date du jour");

        cmbMedoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblNewIdDemande.setText("iddemande");

        lblInfo.setText("             ");

        lblNomEmploye.setText("nomEmploye");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAjouter)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(355, 355, 355)
                        .addComponent(btnQuitter))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblInfo)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblIdDemande)
                                .addComponent(Date)
                                .addComponent(lblNbMedocs)
                                .addComponent(lblQuantite)
                                .addComponent(lblIdEmploye)))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtQuantite)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(jLabel1))
                            .addComponent(cmbMedoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDateJour)
                            .addComponent(lblNewIdDemande)
                            .addComponent(lblNomEmploye))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdDemande)
                    .addComponent(lblNewIdDemande))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Date)
                    .addComponent(lblDateJour))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNbMedocs)
                    .addComponent(cmbMedoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantite)
                    .addComponent(txtQuantite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdEmploye)
                    .addComponent(lblNomEmploye))
                .addGap(18, 18, 18)
                .addComponent(lblInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnQuitter)
                    .addComponent(btnAjouter))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuitterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuitterMouseClicked
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuitterMouseClicked

    private void btnAjouterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAjouterMouseClicked
        int idDemande=Integer.parseInt(lblNewIdDemande.getText());
        int idEmploye=Passerelle.donnerUnIdEmploye(unEmploye.getNom());
        String date=String.valueOf(LocalDate.now());
        int idMedicament=Passerelle.donnerUnIdMedoc(String.valueOf(cmbMedoc.getSelectedItem()));
        int qt=0;
        
        boolean bool=true;
        
        try{
                qt = Integer.parseInt(txtQuantite.getText());
         }
         catch(Exception e){
                bool=false;
                lblInfo.setText("La quantité doit être une valeur numérique");
         }
        
         if(bool){
            unEmploye.setIdEmploye(idEmploye);
            Demande uneDemande=new Demande(idDemande,unEmploye,date,0);
            Medicament unMedicament=new Medicament(idMedicament,null,null,0,null);
            DetailsDemande unDetail=new DetailsDemande(uneDemande,unMedicament,qt);
            boolean fonctionne = Passerelle.ajouterDemande(uneDemande);
            if(fonctionne){
                boolean bool2=Passerelle.ajouterDetailsDemande(unDetail);
                if(bool2==true){
                    lblInfo.setText("Demande ajoutée");
                }
                else{
                    lblInfo.setText("Erreur lors de l'ajout de la quantité de médicament");
                }
            }
            else{
            }
        }
    }//GEN-LAST:event_btnAjouterMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreerDemande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreerDemande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreerDemande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreerDemande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreerDemande().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Date;
    private javax.swing.JButton btnAjouter;
    private javax.swing.JButton btnQuitter;
    private javax.swing.JComboBox<String> cmbMedoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDateJour;
    private javax.swing.JLabel lblIdDemande;
    private javax.swing.JLabel lblIdEmploye;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblNbMedocs;
    private javax.swing.JLabel lblNewIdDemande;
    private javax.swing.JLabel lblNomEmploye;
    private javax.swing.JLabel lblQuantite;
    private javax.swing.JTextField txtQuantite;
    // End of variables declaration//GEN-END:variables
}
