/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pharmacie;

import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author sio2
 */
public class MenuINF extends javax.swing.JFrame {
    private Service leService;
    private Object val;
    private Demande uneDemande;
    private String nomEmploye;
    /**
     * Creates new form Accueil
     */
    
    public String Regex(String chaine){
        String res;
        Pattern p;
        Matcher m;
        p = Pattern.compile("Demande : \\d+");
        m = p.matcher(chaine);
        m.find();
        res = m.group();
        p = Pattern.compile("\\d+");
        m = p.matcher(res);
        m.find();
        res = m.group();
        return res;
    }
    
    public MenuINF(int idService,String nom) {
        initComponents();
        leService = Passerelle.getService(idService);
        lblService.setText(leService.getLibelle());
        lblNomUser.setText(nom);
        nomEmploye=nom;
        DefaultListModel listModel = new DefaultListModel();
        
        String libelle="";
        
        for (Demande demande : Passerelle.donnerLesDemandesParService(leService.getIdService())){
            libelle=Passerelle.getMedocsDemandeParId(demande.getIdDemande());
            listModel.addElement(demande + libelle);
            libelle="";
        }
        lstDemandes.setModel (listModel);
    }
    
    public MenuINF(){
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPasserCmd = new javax.swing.JButton();
        lblNomUser = new javax.swing.JLabel();
        lblNomHopital = new javax.swing.JLabel();
        btnQuitter = new javax.swing.JButton();
        btnSupprimer = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstDemandes = new javax.swing.JList<>();
        lblService = new javax.swing.JLabel();
        btnModifierDemande = new javax.swing.JButton();
        btnVoirDemandes = new javax.swing.JButton();
        txtDemande = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(66, 182, 240));
        setForeground(java.awt.Color.cyan);

        btnPasserCmd.setText("Passer une demande");
        btnPasserCmd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPasserCmdMouseClicked(evt);
            }
        });

        lblNomUser.setText("NOM USER");

        lblNomHopital.setText("Hôpital Jaclet");

        btnQuitter.setText("Quitter");
        btnQuitter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQuitterMouseClicked(evt);
            }
        });
        btnQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitterActionPerformed(evt);
            }
        });

        btnSupprimer.setText("Supprimer une demande");
        btnSupprimer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSupprimerMouseClicked(evt);
            }
        });

        lstDemandes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {"item 1","item 2","item 3","item 4",};
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lstDemandes);

        lblService.setText("Service");

        btnModifierDemande.setText("Modifier une demande");
        btnModifierDemande.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModifierDemandeMouseClicked(evt);
            }
        });

        btnVoirDemandes.setText("Voir les demandes");
        btnVoirDemandes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVoirDemandesMouseClicked(evt);
            }
        });
        btnVoirDemandes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoirDemandesActionPerformed(evt);
            }
        });

        txtDemande.setText("Liste des demandes traitées :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnVoirDemandes)
                                .addGap(18, 18, 18)
                                .addComponent(btnPasserCmd)
                                .addGap(18, 18, 18)
                                .addComponent(btnModifierDemande)
                                .addGap(18, 18, 18)
                                .addComponent(btnSupprimer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnQuitter))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 57, Short.MAX_VALUE)
                                .addComponent(txtDemande)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(49, 49, 49))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblService)
                        .addGap(18, 18, 18)
                        .addComponent(lblNomUser, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblNomHopital, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblService)
                    .addComponent(lblNomUser))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDemande)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPasserCmd)
                    .addComponent(btnQuitter)
                    .addComponent(btnSupprimer)
                    .addComponent(btnVoirDemandes)
                    .addComponent(btnModifierDemande))
                .addGap(31, 31, 31)
                .addComponent(lblNomHopital)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPasserCmdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPasserCmdMouseClicked
        CreerDemande passer = new CreerDemande(nomEmploye);
        passer.setVisible(true);
    }//GEN-LAST:event_btnPasserCmdMouseClicked

    private void btnQuitterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuitterMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnQuitterMouseClicked

    private void btnSupprimerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSupprimerMouseClicked
        String chaine = (String) lstDemandes.getSelectedValue();
        if(chaine != null){
            int idDemande = Integer.parseInt(Regex(chaine));
            Demande uneDemande = Passerelle.donneUneDemande(idDemande);
            Passerelle.supprimerDemande(uneDemande);
            DefaultListModel listModel = new DefaultListModel();
            String libelle;
            for (Demande demande : Passerelle.donnerLesDemandesParService(leService.getIdService())){
            libelle=Passerelle.getMedocsDemandeParId(demande.getIdDemande());
            listModel.addElement(demande + libelle);
            libelle="";
            }
            lstDemandes.setModel (listModel);
        }
        else{
            JOptionPane.showMessageDialog(null,"Veuillez séléctionner un objet dans la liste (en cliquant dessus)");
        }
    }//GEN-LAST:event_btnSupprimerMouseClicked

    private void lstDemandesMouseClicked(java.awt.event.MouseEvent evt) {                                         
    }  

    private void btnQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitterActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnQuitterActionPerformed

    private void btnModifierDemandeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModifierDemandeMouseClicked
        String chaine = lstDemandes.getSelectedValue();
        if(chaine != null){
            Integer idDemande = Integer.parseInt(this.Regex(chaine));
            Demande uneDemande = Passerelle.donneUneDemande(idDemande);
            if (uneDemande != null) {
                ModifierDemande uneFrame = new ModifierDemande(uneDemande);
                uneFrame.setVisible(true);
            }
        }
        else{
            JOptionPane.showMessageDialog(null,"Veuillez séléctionner un objet dans la liste (en cliquant dessus)");
        }
    }//GEN-LAST:event_btnModifierDemandeMouseClicked

    private void btnVoirDemandesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoirDemandesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVoirDemandesActionPerformed

    private void btnVoirDemandesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoirDemandesMouseClicked
        DefaultListModel listModel = new DefaultListModel();
        String libelle;
        for (Demande demande : Passerelle.donnerToutesLesDemandes()) {
            libelle=Passerelle.getMedocsDemandeParId(demande.getIdDemande());
            listModel.addElement(demande + libelle);
            libelle="";
        }
        lstDemandes.setModel(listModel);
    }//GEN-LAST:event_btnVoirDemandesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuINF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuINF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuINF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuINF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuINF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModifierDemande;
    private javax.swing.JButton btnPasserCmd;
    private javax.swing.JButton btnQuitter;
    private javax.swing.JButton btnSupprimer;
    private javax.swing.JButton btnVoirDemandes;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblNomHopital;
    private javax.swing.JLabel lblNomUser;
    private javax.swing.JLabel lblService;
    private javax.swing.JList<String> lstDemandes;
    private javax.swing.JLabel txtDemande;
    // End of variables declaration//GEN-END:variables
}
