/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pharmacie;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author sio2021
 */
public class MenuPH extends javax.swing.JFrame {
    private Service leService;
    
    /**
     * Creates new form Pharmacien
     */
    public String Regex(String motif,String chaine){
        String res;
        Pattern p;
        Matcher m;
        p = Pattern.compile(motif+"\\d+");
        m = p.matcher(chaine);
        m.find();
        res = m.group();
        p = Pattern.compile("\\d+");
        m = p.matcher(res);
        m.find();
        res = m.group();
        return res;
    }
    
    
    public MenuPH(int idService,String nom) {
        initComponents();
        cacherBouton();
        leService = Passerelle.getService(idService);
        lblService.setText(leService.getLibelle());
        lblUser.setText(nom);
    }
    
    public MenuPH() {
        initComponents();
        cacherBouton();
    }
    
    public void cacherBouton(){
        btnValider.setVisible(false);
        btnRefuser.setVisible(false);
        btnModifierStock.setVisible(false);
        btnAjoutFournisseur.setVisible(false);
        btnCreerCommande.setVisible(false);
        btnModifierCommande.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCommande = new javax.swing.JButton();
        btnDemande = new javax.swing.JButton();
        btnFournisseur = new javax.swing.JButton();
        btnStock = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstPharmacie = new javax.swing.JList<>();
        btnQuitter = new javax.swing.JButton();
        btnCreerCommande = new javax.swing.JButton();
        btnAjoutFournisseur = new javax.swing.JButton();
        btnModifierStock = new javax.swing.JButton();
        btnValider = new javax.swing.JButton();
        btnRefuser = new javax.swing.JButton();
        btnModifierCommande = new javax.swing.JButton();
        lblService = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCommande.setText("Voir les commandes");
        btnCommande.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCommandeMouseClicked(evt);
            }
        });

        btnDemande.setText("Voir les demandes");
        btnDemande.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDemandeMouseClicked(evt);
            }
        });

        btnFournisseur.setText("Voir les fournisseurs");
        btnFournisseur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFournisseurMouseClicked(evt);
            }
        });

        btnStock.setText("Voir les stocks");
        btnStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStockMouseClicked(evt);
            }
        });
        btnStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStockActionPerformed(evt);
            }
        });

        lstPharmacie.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {"Appuyer sur les boutons 'Voir les XXX'",};
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstPharmacie);

        btnQuitter.setText("Quitter");
        btnQuitter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQuitterMouseClicked(evt);
            }
        });

        btnCreerCommande.setText("Créer une commande");
        btnCreerCommande.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCreerCommandeMouseClicked(evt);
            }
        });

        btnAjoutFournisseur.setText("Ajout fournisseur");
        btnAjoutFournisseur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAjoutFournisseurMouseClicked(evt);
            }
        });

        btnModifierStock.setText("Modifier Stock");
        btnModifierStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModifierStockMouseClicked(evt);
            }
        });

        btnValider.setText("Valider");
        btnValider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnValiderMouseClicked(evt);
            }
        });

        btnRefuser.setText("Refuser");
        btnRefuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRefuserMouseClicked(evt);
            }
        });

        btnModifierCommande.setText("Modifier Commande");
        btnModifierCommande.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModifierCommandeMouseClicked(evt);
            }
        });

        lblService.setText("jLabel1");

        lblUser.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRefuser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnValider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDemande)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnStock)
                            .addComponent(btnModifierStock))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnFournisseur)
                            .addComponent(btnAjoutFournisseur))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCommande, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCreerCommande, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                            .addComponent(btnModifierCommande, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(btnQuitter)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblService)
                .addGap(18, 18, 18)
                .addComponent(lblUser)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(btnValider)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRefuser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblService)
                            .addComponent(lblUser))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCommande)
                    .addComponent(btnFournisseur)
                    .addComponent(btnStock)
                    .addComponent(btnDemande)
                    .addComponent(btnQuitter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreerCommande)
                    .addComponent(btnModifierStock)
                    .addComponent(btnAjoutFournisseur))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnModifierCommande)
                .addContainerGap())
        );

        btnValider.setVisible(false);
        btnRefuser.setVisible(false);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStockActionPerformed

    private void btnQuitterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuitterMouseClicked
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuitterMouseClicked

    private void btnCommandeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCommandeMouseClicked
        DefaultListModel listModel = new DefaultListModel();
        String libelle;
        for (Commande commande : Passerelle.donnerToutesLesCommandes()) {
            libelle=Passerelle.getMedocsCommandeParId(commande.getRefCommandes());
            listModel.addElement(commande + libelle);
            libelle="";
        }
        lstPharmacie.setModel(listModel);
        cacherBouton();
        btnCreerCommande.setVisible(true);
        btnModifierCommande.setVisible(true);
    }//GEN-LAST:event_btnCommandeMouseClicked

    private void btnCreerCommandeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreerCommandeMouseClicked
        CreerCommande cc = new CreerCommande();
        cc.setVisible(true);
        btnValider.setVisible(false);
        btnRefuser.setVisible(false);
    }//GEN-LAST:event_btnCreerCommandeMouseClicked

    private void btnFournisseurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFournisseurMouseClicked
        DefaultListModel listModel = new DefaultListModel();
        for (String fournisseur : Passerelle.donnerTousLesFournisseurs()) {
            listModel.addElement(fournisseur);
        }
        lstPharmacie.setModel(listModel);
        cacherBouton();
        btnAjoutFournisseur.setVisible(true);
    }//GEN-LAST:event_btnFournisseurMouseClicked

    private void btnStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStockMouseClicked
        DefaultListModel listModel = new DefaultListModel();
        for (Medicament unMedoc : Passerelle.donneLeStock()) {
            listModel.addElement(unMedoc.toStringInfo());
        }
        lstPharmacie.setModel(listModel);
        cacherBouton();
        btnModifierStock.setVisible(true);
    }//GEN-LAST:event_btnStockMouseClicked

    private void btnAjoutFournisseurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAjoutFournisseurMouseClicked
        CreerFournisseur ajoutFournisseur = new CreerFournisseur();
        ajoutFournisseur.setVisible(true);
        btnValider.setVisible(false);
        btnRefuser.setVisible(false);
    }//GEN-LAST:event_btnAjoutFournisseurMouseClicked

    private void btnModifierStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModifierStockMouseClicked
        String chaine = lstPharmacie.getSelectedValue();
        if(chaine != null){
            Integer idMedoc = Integer.parseInt(this.Regex("Id: ", chaine));
            Medicament unMedoc = Passerelle.donneUnMedicament(idMedoc);
            if (unMedoc != null) {
                ModifierStock uneFrame = new ModifierStock(unMedoc);
                uneFrame.setVisible(true);
            }
        }
        else{
            JOptionPane.showMessageDialog(null,"Veuillez séléctionner un objet dans la liste (en cliquant dessus)");
        }
    }//GEN-LAST:event_btnModifierStockMouseClicked

    private void btnDemandeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDemandeMouseClicked
        DefaultListModel listModel = new DefaultListModel();
        String libelle;
        for (Demande demande : Passerelle.donnerToutesLesDemandes()) {
            libelle=Passerelle.getMedocsDemandeParId(demande.getIdDemande());
            listModel.addElement(demande + libelle);
            libelle="";
        }
        lstPharmacie.setModel(listModel);
        this.cacherBouton();
        btnValider.setVisible(true);
        btnRefuser.setVisible(true);
    }//GEN-LAST:event_btnDemandeMouseClicked

    private void btnValiderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnValiderMouseClicked
        int choix = lstPharmacie.getSelectedIndex();
        if(choix != -1){
            String val = lstPharmacie.getModel().getElementAt(choix);
            int unId = Integer.parseInt(Regex("Demande : ",val));
            Demande uneDemande = Passerelle.donneUneDemande(unId);
            Passerelle.validerDemande(uneDemande);
            DefaultListModel listModel = new DefaultListModel();
            String libelle;
            for (Demande demande : Passerelle.donnerToutesLesDemandes()) {
            libelle=Passerelle.getMedocsDemandeParId(demande.getIdDemande());
            listModel.addElement(demande + libelle);
            libelle="";
            }
            lstPharmacie.setModel(listModel);
        }
        else{
            JOptionPane.showMessageDialog(null,"Veuillez séléctionner un objet dans la liste (en cliquant dessus)");
        }
    }//GEN-LAST:event_btnValiderMouseClicked

    private void btnRefuserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRefuserMouseClicked
        int choix = lstPharmacie.getSelectedIndex();
        if(choix != -1){
            String val = lstPharmacie.getModel().getElementAt(choix);
            int unId = Integer.parseInt(Regex("Demande : ",val));
            Demande uneDemande = Passerelle.donneUneDemande(unId);
            Passerelle.refuserDemande(uneDemande);
            DefaultListModel listModel = new DefaultListModel();
            String libelle;
            for (Demande demande : Passerelle.donnerToutesLesDemandes()) {
            libelle=Passerelle.getMedocsDemandeParId(demande.getIdDemande());
            listModel.addElement(demande + libelle);
            libelle="";
            }
            lstPharmacie.setModel(listModel);
        }
        else{
            JOptionPane.showMessageDialog(null,"Veuillez séléctionner un objet dans la liste (en cliquant dessus)");
        }
    }//GEN-LAST:event_btnRefuserMouseClicked

    private void btnModifierCommandeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModifierCommandeMouseClicked
        String chaine = lstPharmacie.getSelectedValue();
        if(chaine != null){
            Integer idCommande = Integer.parseInt(this.Regex("Commande : ", chaine));
            Commande uneCommande = Passerelle.donneUneCommande(idCommande);
            if (uneCommande != null) {
                ModifierCommande uneFrame = new ModifierCommande(uneCommande);
                uneFrame.setVisible(true);
            }
        }
        else{
            JOptionPane.showMessageDialog(null,"Veuillez séléctionner un objet dans la liste (en cliquant dessus)");
        }
        
    }//GEN-LAST:event_btnModifierCommandeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPH().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjoutFournisseur;
    private javax.swing.JButton btnCommande;
    private javax.swing.JButton btnCreerCommande;
    private javax.swing.JButton btnDemande;
    private javax.swing.JButton btnFournisseur;
    private javax.swing.JButton btnModifierCommande;
    private javax.swing.JButton btnModifierStock;
    private javax.swing.JButton btnQuitter;
    private javax.swing.JButton btnRefuser;
    private javax.swing.JButton btnStock;
    private javax.swing.JButton btnValider;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblService;
    private javax.swing.JLabel lblUser;
    private javax.swing.JList<String> lstPharmacie;
    // End of variables declaration//GEN-END:variables
}
